spring:
  application:
    name: second-brain-rag
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB  

  sql:
    init:
      mode: never

  mvc:
    async:
      request-timeout: 3600000 # 1 hour for long embedding processes

  datasource:
    url: jdbc:postgresql://db.fyfvyxztprbllrhslnnj.supabase.co:5432/postgres
    username: postgres
    password: ${DB_BRAIN_RAG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: false
    cohere:
      api-key: ${COHERE_API_KEY}

server:
  port: ${PORT:8080}
  tomcat:
    connection-timeout: 3600000 # 1 hour
    max-swallow-size: 50MB

logging:
  level:
    org.springframework.ai: DEBUG
