spring:
  application:
    name: second-brain-rag
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  datasource:
    url: jdbc:postgresql://db.fyfvyxztprbllrhslnnj.supabase.co:5432/postgres
    username: postgres
    password: ${DB_BRAIN_RAG_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: true

logging:
  level:
    org.springframework.ai: DEBUG
